#!/bin/bash

ROOT=`pwd`

BAZEL_DEPS_REPO="https://github.com/input-output-hk/bazel-deps.git"
BAZEL_DEPS_TAG="latest"
IDENTIFIER="$BAZEL_DEPS_REPO|$BAZEL_DEPS_TAG"
SHASUM="sha256sum"
unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)    SHASUM="shasum -a256";;
esac

BAZEL_DEPS="/tmp/$(echo "$IDENTIFIER" | ${SHASUM} | awk '{ print $1 }')/.bazel-deps/"

function fail() {
  echo "$1"
  exit 1
}

if [ -e $BAZEL_DEPS ]; then
    if [ ! -d $BAZEL_DEPS ]; then
        echo "'deps' expects to find 'bazel-deps' in the '$BAZEL_DEPS' folder"
        echo "or to clone it there. But right now something that is not a directory"
        echo "exists there"
        exit 1
    fi
    cd "$BAZEL_DEPS"
else
    git clone "$BAZEL_DEPS_REPO" "$BAZEL_DEPS" || fail "Repo could not be found"
    cd "$BAZEL_DEPS"
fi

git checkout "$BAZEL_DEPS_TAG" || fail "Tag could not be found"

bazel run //:parse -- generate --repo-root $ROOT --deps "$ROOT/dependencies.yaml" --external 3rdparty 
