#!/bin/bash

ROOT=`pwd`

BAZEL_DEPS_REPO="https://github.com/marcesquerra/bazel-deps.git"
BAZEL_DEPS_COMMIT="b9baec69bdbaae53743a7c0b69828a9c66f6a624"
IDENTIFIER="$BAZEL_DEPS_REPO|$BAZEL_DEPS_COMMIT"

BAZEL_DEPS="/tmp/$(echo "$IDENTIFIER" | sha256sum | awk '{ print $1 }')/.bazel-deps/"

function fail() {
  echo "$1"
  exit 1
}

if [ -e $BAZEL_DEPS ]; then
    if [ ! -d $BAZEL_DEPS ]; then
        echo "'deps' expects to find 'bazel-deps' in the '$BAZEL_DEPS' folder"
        echo "or to clone it there. But right now something that is not a directory"
        echo "exists there"
        exit 1
    fi
    cd "$BAZEL_DEPS"
else
    git clone "$BAZEL_DEPS_REPO" "$BAZEL_DEPS" || fail "Repo could not be found"
    cd "$BAZEL_DEPS"
    git checkout "$BAZEL_DEPS_COMMIT" || fail "Commit could not be found"
fi

bazel run //:parse -- generate --repo-root $ROOT --deps "$ROOT/dependencies.yaml" --external 3rdparty 
