#!/usr/bin/env bash

set -euv

if [[ "$CIRCLE_BRANCH" == "develop" ]]; then

echo $GPG_KEY | base64 --decode | gpg --batch --import

gpg --passphrase $GPG_PASSPHRASE --batch --yes -a -b LICENSE

mill mill.scalalib.PublishModule/publishAll \
    __.publishArtifacts \
    "$OSS_USERNAME":"$OSS_PASSWORD" \
    --gpgArgs --passphrase="$GPG_PASSPHRASE",--batch,--yes,-a,-b

else

  echo "Skipping publish step"

fi
